## arra数组的数值计算

In [1]:
import numpy as np
pu_arr = np.array([[1,2,3],[4,5,6]])
pu_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.sum(pu_arr)

21

指定要进行的操作是沿着什么维度（什么轴）

In [3]:
np.sum(pu_arr,axis=0)

array([5, 7, 9])

In [4]:
pu_arr.ndim

2

In [5]:
np.sum(pu_arr, axis=1)

array([ 6, 15])

In [6]:
np.sum(pu_arr, axis=-1)

array([ 6, 15])

In [7]:
pu_arr.sum()

21

In [8]:
pu_arr.sum(axis=0)

array([5, 7, 9])

乘积

In [9]:
pu_arr.prod()

720

In [10]:
pu_arr.prod(axis=0)

array([ 4, 10, 18])

In [11]:
pu_arr.prod(axis=-1)

array([  6, 120])

最小值

In [12]:
pu_arr.min()

1

In [13]:
pu_arr.min(axis=1)

array([1, 4])

In [14]:
pu_arr.max()

6

找最小值的索引

In [15]:
pu_arr.argmin()

0

In [16]:
pu_arr.argmin(axis=1)

array([0, 0], dtype=int64)

算均值

In [17]:
pu_arr.mean()

3.5

In [18]:
pu_arr.mean(axis=1)

array([2., 5.])

算标准差

In [19]:
pu_arr.std()

1.707825127659933

In [20]:
pu_arr.std(axis=0)

array([1.5, 1.5, 1.5])

算方差

In [21]:
pu_arr.var()

2.9166666666666665

限制：小于最小给定值的都变成这个最小值；大于最大给定值的都变成这个最大值

In [22]:
pu_arr.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

四舍五入

In [23]:
pu_arr = np.array([1,2,3.56,6.41])
pu_arr.round()

array([1., 2., 4., 6.])

In [24]:
pu_arr.round(decimals=1)

array([1. , 2. , 3.6, 6.4])

## 排序

In [25]:
pu_arr = np.array([[1.5,1.3,7.5],[5.6,7.8,1.2]])
pu_arr

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [26]:
np.sort(pu_arr)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [27]:
np.sort(pu_arr, axis=0)  # 默认值axis=0

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

argsort() : 这个函数表示先排序，然后找位置

In [28]:
np.argsort(pu_arr)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

Linspace() : 按照平均差异构造数

In [29]:
pu_arr = np.linspace(0,10,10)  # 零到十之间平均的选十个数
pu_arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
values = np.array([2.5, 6.5, 9.5])

In [31]:
np.searchsorted(pu_arr, values)

array([3, 6, 9], dtype=int64)

返回的值，就是顺序排列后，该插入的位置。但有个前提是searchsorted()要使用的数组是顺序排列的。That is why it is "sorted"

In [32]:
pu_arr = np.array([[1,0,6], [1,7,0], [2,3,1], [2,4,0]])
pu_arr

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

## 数组形状

In [33]:
pu_arr = np.arange(10)  # 等差数列
pu_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
pu_arr.shape

(10,)

通过这个函数来改这个数组的形状

In [35]:
pu_arr.shape = 2, 5

In [36]:
pu_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
pu_arr.reshape(1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

数组大小不能被改变，不能随意换shape

In [40]:
pu_arr.shape = 4, 4

ValueError: cannot reshape array of size 10 into shape (4,4)

扩充维度

In [41]:
pu_arr = np.arange(10)
pu_arr.shape

(10,)

In [42]:
pu_arr = pu_arr[np.newaxis, :]
pu_arr.shape

(1, 10)

In [43]:
pu_arr = pu_arr[np.newaxis, np.newaxis, :]
pu_arr.shape

(1, 1, 1, 10)

降低维度，自动把空轴去掉

In [44]:
pu_arr = pu_arr.squeeze()
pu_arr.shape

(10,)

数组转置

In [45]:
pu_arr = np.arange(10)
pu_arr.shape = 2, 5
pu_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
pu_arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

有个简单写法，直接一个T。注意转置操作之后原数组还是不变的。

In [47]:
pu_arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [48]:
pu_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要想原数组也转置就进行一个赋值操作

In [49]:
pu_arr = pu_arr.transpose()
pu_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## 数组连接

In [50]:
a = np.array([[123,456,789,],[3214,456,134]])
a

array([[ 123,  456,  789],
       [3214,  456,  134]])

In [51]:
b = np.array([[333,6676,7569,],[34564,6876,5664]])
b

array([[  333,  6676,  7569],
       [34564,  6876,  5664]])

两数组shape相同

In [52]:
c = np.concatenate((a,b))  # 别忘记这里有两个括号，第一个括号是为了传参
c

array([[  123,   456,   789],
       [ 3214,   456,   134],
       [  333,  6676,  7569],
       [34564,  6876,  5664]])

默认是按第一个维度拼接

In [53]:
c = np.concatenate((a,b), axis=1)  # 别忘记这里有两个括号，第一个括号是为了传参
c

array([[  123,   456,   789,   333,  6676,  7569],
       [ 3214,   456,   134, 34564,  6876,  5664]])

还有一种拼接方式，利用vstack和hstack来拼接

In [54]:
np.vstack((a, b))

array([[  123,   456,   789],
       [ 3214,   456,   134],
       [  333,  6676,  7569],
       [34564,  6876,  5664]])

In [55]:
np.hstack((a, b))

array([[  123,   456,   789,   333,  6676,  7569],
       [ 3214,   456,   134, 34564,  6876,  5664]])

还能拉平

In [56]:
a

array([[ 123,  456,  789],
       [3214,  456,  134]])

In [57]:
a.flatten()

array([ 123,  456,  789, 3214,  456,  134])

In [58]:
a

array([[ 123,  456,  789],
       [3214,  456,  134]])

In [59]:
a.ravel()  # 也是拉平操作

array([ 123,  456,  789, 3214,  456,  134])