## 数组生成函数

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

构造数组

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [4]:
np.arange(4, 10, 2, dtype=np.float32)

array([4., 6., 8.], dtype=float32)

linspace() : 构造等距分布，但是包含头尾（更像是把最后一个数给四舍五入了）

In [5]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

logspace() : 
在对数尺度上返回间隔均匀的数字。

在线性空间中，序列从base ** start（以start的幂为基础）开始，并以base ** stop结束。

默认是以10为底的

np.linspace(start, stop, num=num, endpoint=endpoint)

In [6]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

网格

In [7]:
x = np.linspace(-10, 10, 5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
y = np.linspace(-10, 10, 5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [9]:
x, y = np.meshgrid(x, y)

In [10]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [11]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

向量

In [12]:
np.r_[0:10]  # 行向量

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.c_[0:10] # 列向量

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

更常用的zeros, ones矩阵，用在做初始化上

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((3, 3)) * 2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [18]:
np.ones((3, 3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

这是另一种做初始化的方法

In [19]:
x = np.empty(4)
x.shape

(4,)

In [20]:
x.fill(1)
x

array([1., 1., 1., 1.])

已有一个矩阵，来用zores_like和ones_like来做类似的空矩阵

In [21]:
pu_arr = np.array([1,2,3,4])
pu_arr

array([1, 2, 3, 4])

In [22]:
np.zeros_like(pu_arr)

array([0, 0, 0, 0])

In [23]:
np.ones_like(pu_arr)

array([1, 1, 1, 1])

生成一个单位矩阵

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])