## 四则运算

In [1]:
import numpy as np

In [2]:
y = np.array([2,2])
x = np.array([5,5])

In [3]:
np.multiply(x, y)

array([10, 10])

要能计算dot维度得相同

In [4]:
np.dot(x,y)

20

In [5]:
x.shape = 2, 1

In [6]:
x

array([[5],
       [5]])

In [7]:
np.dot(x, y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [8]:
y.shape = 1, 2
y

array([[2, 2]])

In [9]:
x

array([[5],
       [5]])

In [10]:
np.dot(x, y)

array([[10, 10],
       [10, 10]])

In [11]:
np.dot(y, x)

array([[20]])

直接用*的话，numpy会自动做一个转换，比如把一维帮你再扩充到二维。但一般不用这个

In [12]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
x * y

array([[1, 2, 3],
       [4, 5, 6]])

## 逻辑运算

In [13]:
x = np.array([1,1,1])
y = np.array([1,1,2])
x == y

array([ True,  True, False])

In [14]:
np.logical_and(x, y)

array([ True,  True,  True])

In [15]:
np.logical_or(x, y)

array([ True,  True,  True])

In [16]:
np.logical_not(x, y)

array([0, 0, 0])