## 随机模块

在某阶段的开始不知道是何状态，这时候要做初始化，就要用随机模块

In [1]:
import numpy as np

所有的值都是从零到1的

In [2]:
np.random.rand(3,2)  # 构造浮点数 ()里填size值也就是shape什么样

array([[0.11145921, 0.53921376],
       [0.79300374, 0.00424424],
       [0.86000107, 0.53638406]])

In [3]:
np.random.rand()

0.6932165020557556

In [4]:
np.random.randint(10, size=(5,4))  # 10表示从0到10的意思
# 而且是左闭右开区间

array([[3, 8, 6, 1],
       [4, 0, 9, 4],
       [1, 1, 3, 5],
       [2, 3, 9, 6],
       [8, 7, 3, 2]])

In [5]:
np.random.random_sample()  # 浮点数随机数的另一种写法

0.5219795379892593

In [6]:
np.random.randint(0,10,3)

array([4, 7, 8])

高斯分布,构造一个满足于高斯分布的序列

In [7]:
mu, sigma = 0, 0.1

In [8]:
np.random.normal(mu, sigma, 10)

array([-0.00815153,  0.09024796, -0.02802105, -0.03720646, -0.03581701,
       -0.08858312,  0.08835106,  0.10761092,  0.02477139, -0.00688366])

如果觉得小数点位数太长了，可以在np中设置参数

In [9]:
np.set_printoptions(precision=3)

In [10]:
np.random.normal(mu, sigma, 10)

array([-0.028, -0.116, -0.126,  0.013,  0.023, -0.038, -0.046,  0.004,
       -0.016, -0.035])

洗牌  
数据本身有前后依存关系时，希望重新洗牌，打乱顺序，很常见的操作

In [11]:
pu_arr = np.arange(10)
pu_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(pu_arr)
pu_arr

array([4, 1, 6, 5, 8, 2, 3, 7, 9, 0])

如果像按照某种模式进行随机，这里需要用到`随机种子`

In [13]:
np.random.seed(0)
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 10)

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])

之前的随机，只要再执行一次就会出现不一样的随即结果。但是当指定了种子之后，这个随机模式就不改变了，重复多少变，结果都不变的。在对比实验中，这个用在想要观察两组数据在相同的随机模式下变化的不同时很方便，相当于控制了变量

## 文件读写操作

In [14]:
import numpy as np

In [15]:
%%writefile writefile.txt
1 2 3 4 5 6
1 4 3 5 5 2

Overwriting writefile.txt


正常情况下的python的文件读取

In [16]:
data = []
with open('writefile.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [1., 4., 3., 5., 5., 2.]])

numpy的读取

In [17]:
data = np.loadtxt('writefile.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [1., 4., 3., 5., 5., 2.]])

默认都是以空格为分隔符，要是以逗号为分隔符，则一般读取方法已经不能用了，利用delimiter()

In [18]:
%%writefile writefile.txt
1, 2, 3, 4, 5, 6
1, 4, 3, 5, 5, 2

Overwriting writefile.txt


In [19]:
data = np.loadtxt('writefile.txt', delimiter = ',')
data

array([[1., 2., 3., 4., 5., 6.],
       [1., 4., 3., 5., 5., 2.]])

还可以去掉第一排，使用skiprows()去掉几行

In [20]:
%%writefile writefile.txt
x, y, z, w, a, b
1, 2, 3, 4, 5, 6
1, 4, 3, 5, 5, 2

Overwriting writefile.txt


In [21]:
data = np.loadtxt('writefile.txt', delimiter = ',', skiprows = 1)
data

array([[1., 2., 3., 4., 5., 6.],
       [1., 4., 3., 5., 5., 2.]])

* 此外，还有usecols：指定使用哪几列

写入文件，用numpy来写

In [22]:
pu_arr = np.array([[1,2,3],[4,5,6]])

In [23]:
np.savetxt('writefile.txt', pu_arr)

In [24]:
# %load writefile.txt
1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00


SyntaxError: invalid syntax (3069495313.py, line 2)

写出来的东西太长了，可以再加一个参数

In [25]:
np.savetxt('writefile.txt', pu_arr, fmt='%d')

In [27]:
# %load writefile.txt
1 2 3
4 5 6


如果想用逗号做分隔符也可以

In [28]:
np.savetxt('writefile.txt', pu_arr, fmt='%d', delimiter=',')

In [29]:
# %load writefile.txt
1,2,3
4,5,6


保留两位小数

In [30]:
np.savetxt('writefile.txt', pu_arr, fmt='%.2f')

In [31]:
# %load writefile.txt
1.00 2.00 3.00
4.00 5.00 6.00


## 读写联动
重要的文件需要在操作过程中去保存

In [42]:
pu_arr = np.array([[1,2,3],[4,5,6]])
np.save('pu_arr.npy', pu_arr)

In [43]:
pu = np.load('pu_arr.npy')
pu

array([[1, 2, 3],
       [4, 5, 6]])

两个数据要保存在同一个地方，可以用savez把它们做成一个压缩文件

In [50]:
pu = np.array([1,2,3])
np.savez('pu.npz', a=pu_arr, b=pu)

In [51]:
data = np.load('pu.npz')

In [52]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x0000018CABD0B760>)

In [53]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
data['b']

array([1, 2, 3])